---
- name: Harbor Yard converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: common
    - role: docker
    - role: secrets
      tags: [secrets]
    - role: stacks
    - role: pull_timer
      tags: [pull_timer]
